cc_library(
    name = "sobel",
    # srcs = ["sobel_omp.c", "sobel_seq.c"],
    srcs = ["sobel_seq.c"],
    hdrs = ["sobel.h"],
    visibility = ["//main:__pkg__"],
    deps = [
        "//lib/img:img",
    ],
)
